### ISSUE TITLE
Improve email template in postmark to include location information from CF headers, agent information and validation phrase

### ISSUE THREAD

**Issue by hugomrdias** [web3-storage/w3protocol#347]
More context for this issue here https://purrfect-tracker-45c.notion.site/Email-auth-flow-d33f0715024a47c18a8114ba284e9c07
Example:
<img width="593" alt="Screenshot 2023-01-12 at 16 44 58" src="https://user-images.githubusercontent.com/314190/212730941-a7c3079f-a0a0-418a-a8a5-f50b9bd9228c.png">

Email should include:

- [ ] Location info
- [ ] Agent information
- [ ] Validation phrase (generate in the backend)
- [ ] Validation phrase should be printed in the agent requesting the email flow
- [x] Copy template to GH repo and maintain there (manual copy-paste to Postmark)
  - [x] check if postmark supports templates in github instead of theirs dashboard.

**Comment by natevw** [comment]
The work in #399 should resolve the second half of your checklist:

- [ ] Location info
- [ ] Agent information
- [x] Validation phrase (generate in the backend)
- [x] Validation phrase should be printed in the agent requesting the email flow
- [x] Copy template to GH repo and maintain there (manual copy-paste to Postmark)
 check if postmark supports templates in github instead of theirs dashboard.

Although the "printed in the agent" part is mostly on the `w3ui` side tracked as https://github.com/web3-storage/w3ui/issues/307, the work on the API shouldn't break the protocol as long as the user will just click the approve link without being able to see the phrase in the client yet.

**Comment by heyjay44** [comment]
New PR is here: https://github.com/web3-storage/w3protocol/pull/432

**Comment by heyjay44** [comment]
I'm creating a new issue to reflect our needs better.
